package utils.guicomponents.table;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JPanel;
import javax.swing.SwingConstants;

import utils.guicomponents.MyImageIcon;

/**
 *
 * @author RAVEN
 */
public class PanelAction extends JPanel {

    private boolean tonTaiNutSua;
	/**
     * Creates new form PanelAction
     */
    public PanelAction(boolean tonTaiNutXoa, boolean tonTaiNutSua) {
    	this.tonTaiNutXoa = tonTaiNutXoa;
    	this.tonTaiNutSua = tonTaiNutSua;
        initComponents();
    }

    public void initEvent(TableActionEvent event, int row) {
        cmdEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onEdit(row);
            }
        });
        cmdDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDelete(row);
            }
        });
        cmdView.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onView(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdEdit = new ActionButton();
        cmdDelete = new ActionButton();
        cmdView = new ActionButton();

        cmdEdit.setIcon(new MyImageIcon("src/main/resources/images/icons/edit.png")); // NOI18N

        cmdDelete.setIcon(new MyImageIcon("src/main/resources/images/icons/delete.png")); // NOI18N

        cmdView.setIcon(new MyImageIcon("src/main/resources/images/icons/view.png")); // NOI18N

        this.add(cmdView);
        if(tonTaiNutXoa) this.add(cmdDelete);
        if(tonTaiNutSua) this.add(cmdEdit);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ActionButton cmdDelete;
    private ActionButton cmdEdit;
    private ActionButton cmdView;
    private boolean tonTaiNutXoa;
    // End of variables declaration//GEN-END:variables
}
